In [2]:
# Useful starting lines
%matplotlib inline
import numpy as np
import matplotlib.pyplot as plt
%load_ext autoreload
%autoreload 2

In [3]:
from proj1_helpers import *
DATA_TRAIN_PATH = 'data/train.csv' # TODO: download train data and supply path here 
y, tX, ids = load_csv_data(DATA_TRAIN_PATH)

In [4]:
tX

array([[ 138.47 ,   51.655,   97.827, ...,    1.24 ,   -2.475,  113.497],
       [ 160.937,   68.768,  103.235, ..., -999.   , -999.   ,   46.226],
       [-999.   ,  162.172,  125.953, ..., -999.   , -999.   ,   44.251],
       ...,
       [ 105.457,   60.526,   75.839, ..., -999.   , -999.   ,   41.992],
       [  94.951,   19.362,   68.812, ..., -999.   , -999.   ,    0.   ],
       [-999.   ,   72.756,   70.831, ..., -999.   , -999.   ,    0.   ]])

In [5]:
tX.shape

(250000, 30)

In [6]:
print([tX[:, col].dtype for col in range(30)])

[dtype('float64'), dtype('float64'), dtype('float64'), dtype('float64'), dtype('float64'), dtype('float64'), dtype('float64'), dtype('float64'), dtype('float64'), dtype('float64'), dtype('float64'), dtype('float64'), dtype('float64'), dtype('float64'), dtype('float64'), dtype('float64'), dtype('float64'), dtype('float64'), dtype('float64'), dtype('float64'), dtype('float64'), dtype('float64'), dtype('float64'), dtype('float64'), dtype('float64'), dtype('float64'), dtype('float64'), dtype('float64'), dtype('float64'), dtype('float64')]


In [7]:
np.count_nonzero(tX == -999, axis=0)

array([ 38114,      0,      0,      0, 177457, 177457, 177457,      0,
            0,      0,      0,      0, 177457,      0,      0,      0,
            0,      0,      0,      0,      0,      0,      0,  99913,
        99913,  99913, 177457, 177457, 177457,      0])

In [8]:
row_nan_pct = np.count_nonzero(tX == -999, axis=0) / len(tX)

In [9]:
row_nan_pct 

array([0.152456, 0.      , 0.      , 0.      , 0.709828, 0.709828,
       0.709828, 0.      , 0.      , 0.      , 0.      , 0.      ,
       0.709828, 0.      , 0.      , 0.      , 0.      , 0.      ,
       0.      , 0.      , 0.      , 0.      , 0.      , 0.399652,
       0.399652, 0.399652, 0.709828, 0.709828, 0.709828, 0.      ])

In [10]:
np.count_nonzero(row_nan_pct == 0)

19

In [11]:
non_nan_cols = (row_nan_pct == 0)

In [12]:
non_nan_cols

array([False,  True,  True,  True, False, False, False,  True,  True,
        True,  True,  True, False,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True, False, False, False, False,
       False, False,  True])

In [27]:
tX_new = tX[:, non_nan_cols]

In [28]:
tX_new.shape

(250000, 19)

In [29]:
from implementations import standardize_data, add_bias, encode_binary
tX_new = standardize_data(tX_new)
tX_new = add_bias(tX_new)
y_new = encode_binary(y)
y_new = y_new.reshape((-1, 1))

In [30]:
y_new

array([[1.],
       [0.],
       [0.],
       ...,
       [1.],
       [0.],
       [0.]])

In [31]:
tX_new

array([[ 1.        ,  0.06833197,  0.40768027, ...,  0.38684673,
         1.04440205,  0.4125105 ],
       [ 1.        ,  0.55250482,  0.54013641, ..., -0.35771893,
         0.02130497, -0.27381996],
       [ 1.        ,  3.19515553,  1.09655998, ...,  0.40013535,
         0.02130497, -0.29396985],
       ...,
       [ 1.        ,  0.31931645, -0.13086367, ..., -0.08608887,
         0.02130497, -0.31701723],
       [ 1.        , -0.84532397, -0.30297338, ..., -0.76742886,
        -1.00179211, -0.74543941],
       [ 1.        ,  0.66533608, -0.25352276, ..., -0.87267059,
        -1.00179211, -0.74543941]])

In [71]:
from implementations import logistic_regression_cv
weights, loss, lambda_, degree, accuracy, f1 = logistic_regression_cv(y_new, tX_new, verbose=False)

Best Accuracy : 71.9705% reached at epoch 99
Best Accuracy : 72.78999999999999% reached at epoch 99
Best Accuracy : 70.928% reached at epoch 99
Best Accuracy : 71.0095% reached at epoch 99
Best Accuracy : 71.3965% reached at epoch 99
Best Accuracy : 71.75200000000001% reached at epoch 99
Best Accuracy : 72.49849999999999% reached at epoch 99
Best Accuracy : 70.9305% reached at epoch 99
Best Accuracy : 70.49% reached at epoch 99
Best Accuracy : 70.59% reached at epoch 99
Best Accuracy : 71.30250000000001% reached at epoch 99
Best Accuracy : 70.9945% reached at epoch 99
Best Accuracy : 70.1145% reached at epoch 99
Best Accuracy : 71.6985% reached at epoch 99
Best Accuracy : 72.30799999999999% reached at epoch 99
Best Accuracy : 71.41300000000001% reached at epoch 97
Best Accuracy : 71.17750000000001% reached at epoch 99
Best Accuracy : 71.2445% reached at epoch 99
Best Accuracy : 71.63199999999999% reached at epoch 73
Best Accuracy : 71.37299999999999% reached at epoch 99
Best Accuracy :

In [72]:
weights, loss, lambda_, degree, accuracy, f1

(array([[ 0.16329277],
        [-0.21104522],
        [ 0.28567849],
        [ 0.22470116],
        [ 0.71394256],
        [-0.07669442],
        [-0.06627629],
        [-0.2318925 ],
        [ 0.51841159],
        [ 0.72452699],
        [ 0.06499176],
        [ 0.07855991],
        [ 0.34549131],
        [ 0.09909849],
        [ 0.03322264],
        [ 0.06765302],
        [ 0.05585609],
        [-0.20235065],
        [ 0.22499467],
        [ 0.24488963],
        [-0.25501935],
        [-0.00732738],
        [-0.6583855 ],
        [ 0.04588794],
        [-0.13872242],
        [ 0.02810542],
        [-0.23118199],
        [-0.03120961],
        [ 0.083453  ],
        [-0.04204543],
        [-0.13182436],
        [-0.13157164],
        [ 0.04692292],
        [-0.08998494],
        [-0.05071935],
        [ 0.040988  ],
        [ 0.15204274],
        [ 0.09663278],
        [-0.10903318],
        [ 0.0087319 ]]),
 0.4920579338000885,
 0.01,
 2,
 76.0068,
 0.7001770317208813)

In [73]:
DATA_TEST_PATH = 'data/test.csv' # TODO: download train data and supply path here 
_, tX_test, ids_test = load_csv_data(DATA_TEST_PATH)

In [74]:
tX_test = tX_test[:, non_nan_cols]
tX_test = standardize_data(tX_test)
tX_test = add_bias(tX_test)

In [75]:
tX_test

array([[ 1.        ,  0.85695592, -1.41340956, ..., -0.87748396,
        -1.00087589, -0.74405712],
       [ 1.        ,  0.51511285,  0.16866785, ..., -0.26550003,
         0.02016428, -0.26091718],
       [ 1.        ,  0.19686173,  0.37643086, ..., -0.77548795,
        -1.00087589, -0.74405712],
       ...,
       [ 1.        , -1.1138051 , -0.39465676, ..., -0.16785199,
        -1.00087589, -0.74405712],
       [ 1.        , -0.82649192, -0.35035672, ...,  0.02053619,
         0.02016428, -0.4306331 ],
       [ 1.        ,  0.87164791, -0.08655773, ..., -0.88675489,
        -1.00087589, -0.74405712]])

In [66]:
from implementations import build_poly
tX_test = build_poly(tX_test, degree)

In [67]:
tX_test.shape

(568238, 60)

In [68]:
from datetime import datetime
from implementations import predict
method = 'logistic_regression'
time = datetime.now().strftime('%Y%m%dH%H%M%S')
OUTPUT_PATH = f'submissions/submission_{method}_{time}' # TODO: fill in desired name of output file for submission
y_pred = predict(weights, tX_test)
y_pred[np.where(y_pred == 0)] = -1
create_csv_submission(ids_test, y_pred, OUTPUT_PATH)

In [52]:
corrs = []
for i in range(tX.shape[1]):
    corrs.append(np.corrcoef(tX[:, i], y)[0, 1])

In [53]:
sorted(corrs)

[-0.3514279558616751,
 -0.19539789618287817,
 -0.031947586805348205,
 -0.015287426687781413,
 -0.014055273784852506,
 -0.0044025386863883985,
 -0.0009432510582117487,
 0.0015162353770597236,
 0.0041254474115248515,
 0.0074753421885902374,
 0.012245481285482902,
 0.02246575151078583,
 0.13354912308169134,
 0.13429572666925302,
 0.1355202615226846,
 0.14055440046509557,
 0.1407143669504368,
 0.14125568650533774,
 0.1412649137760153,
 0.14134598859646297,
 0.1416459925656641,
 0.15046803779292678,
 0.15046926004977906,
 0.1532359324758135,
 0.15760414567634926,
 0.19176608807477077,
 0.19252632856874796,
 0.23523797587836723,
 0.23914905789154473,
 0.2717518770516493]