In [1]:
# Useful starting lines
%matplotlib inline
import numpy as np
import matplotlib.pyplot as plt
%load_ext autoreload
%autoreload 2

In [2]:
from proj1_helpers import *
DATA_TRAIN_PATH = 'data/train.csv' # TODO: download train data and supply path here 
y_train, X_train, ids = load_csv_data(DATA_TRAIN_PATH)

In [3]:
DATA_TEST_PATH = 'data/test.csv' # TODO: download train data and supply path here 
_, X_test, ids_test = load_csv_data(DATA_TEST_PATH)

In [4]:
from implementations import read_header
features = read_header(DATA_TRAIN_PATH)

In [5]:
features.index('PRI_jet_num')

22

In [8]:
jet_nums = X_train[:, features.index('PRI_jet_num')]

In [9]:
np.unique(jet_nums)

array([0., 1., 2., 3.])

In [17]:
jet_num_encodings = []
for jet_num in np.unique(jet_nums):
    jet_num_values = np.where(jet_nums == jet_num, 1, 0)
    jet_num_encodings.append(jet_num_values.reshape((-1, 1)))

In [18]:
np.hstack(jet_num_encodings)

array([[0, 0, 1, 0],
       [0, 1, 0, 0],
       [0, 1, 0, 0],
       ...,
       [0, 1, 0, 0],
       [1, 0, 0, 0],
       [1, 0, 0, 0]])

In [11]:
jet_nums

array([2., 1., 1., ..., 1., 0., 0.])

In [ ]:
from implementations import preprocess
tX_train, ty_train, tX_test, ty_test, cont_features = preprocess(X_train, y_train, X_test, encodable_threshold=0.5, imputable_threshold=0.5)

In [ ]:
tX_train.shape

In [ ]:
fig, axs = plt.subplots(11, 3, figsize=(16, 50))

for i in range(tX_train.shape[1]):
    ax = axs[i//3, i%3]
    ax.hist(tX_train[:, i])
    ax.set_yscale('log')
    # ax.set_title(features[i])

plt.show()

In [ ]:
positive_cols = [1, 2, 3, 8, 9, 10, 13, 16, 19, 21, 29]

In [ ]:
np.log(X_train[positive_cols])

In [ ]:
fig, axs = plt.subplots(10, 3, figsize=(16, 50))

for i in range(X_train.shape[1]):
    ax = axs[i//3, i%3]
    ax.hist(X_train[:, i])
    ax.set_yscale('log')
    ax.set_title(features[i])

plt.show()

In [ ]:
derived_cols = list(range(13))
raw_cols = list(range(13, 30))

In [ ]:
import seaborn as sns
import pandas as pd
int_cols = [0, 1, 2, 5, 7, 9, 10, 11]
sns.pairplot(pd.DataFrame(np.hstack([X_train[:, int_cols], y_train.reshape((-1, 1))]), columns=list(np.array(features).take(int_cols))+['Label']), hue='Label')

In [ ]:
fig, axs = plt.subplots(17, 2, figsize=(16, 50))

for i in range(tX_train.shape[1]):
    ax = axs[i//2, i%2]
    ax.hist(tX_train[:, i])
    ax.set_yscale('log')
    # ax.set_title(features[i])

plt.show()

In [ ]:
skewed_cols = [1,2,3,6,7,9,12,17,19,20,21]
binned_cols = []
for c in skewed_cols:
    bins = np.linspace(np.min(tX_train[:, c]), np.max(tX_train[:, c]), 10)
    digitized_col = np.digitize(tX_train[:, c], bins)
    binned_cols.append(digitized_col.reshape((-1, 1)))

In [ ]:
binned_X = np.hstack(binned_cols)
tX_train = np.hstack([tX_train, binned_X])

In [ ]:
corrs = []
for i in range(X_train.shape[1]):
    corrs.append(np.corrcoef(X_train[:, i].reshape((-1, 1)), y_train.reshape((-1, 1)))[0, 1])