# Preprocessing and Feature Engineering
This notebook contains the code for preprocessing and feature engineering steps.

In [2]:
# Useful starting lines
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import random as rd
import seaborn as sns
%matplotlib inline
%load_ext autoreload
%autoreload 2
import sys
sys.path.append('..')
from helpers import *
from implementations import *

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [3]:
DATA_TRAIN_PATH = '../data/train.csv' # TODO: download train data and supply path here 
y, tX, ids = load_csv_data(DATA_TRAIN_PATH)

with open(DATA_TRAIN_PATH) as f:
    labels = f.readline().split(',')[2:] #remove 2 first, being ID and prediction
df = pd.read_csv(DATA_TRAIN_PATH)


## Prepare subsets of data based on the number of jets

In [5]:
X_zero, y_zero, X_one, y_one, X_many, y_many = split_by_jet_num(DATA_TRAIN_PATH, tX, y)

Let's check the ratio of nan values for each column now.

In [6]:
compute_nan_ratio(replace_values(X_zero, -999, np.nan))

array([0.26145747, 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ])

In [7]:
compute_nan_ratio(replace_values(X_one, -999, np.nan))

array([0.09751883, 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        ])

In [8]:
compute_nan_ratio(replace_values(X_many, -999, np.nan))

array([0.06105344, 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        ])